### ISSUE TITLE
小伙，很粗心啊！

### ISSUE THREAD

**Issue by god8891** [V-Tom/react-blog#1]
{
                test: /\.stylus$/,
                loader: ExtractTextPlugin.extract("style-loader", "css-loader!stylus-loader?sourceMap")
            }

应该改为

{
                test: /\.styles$/,
                loader: ExtractTextPlugin.extract("style-loader", "css-loader!stylus-loader?sourceMap")
            }

**Comment by V-Tom** [comment]
这里是使用的`stylus`预处理器
见：[stylus lang](http://stylus-lang.com/)
